version: '3.8'

services:
  app:
    build: .
    container_name: study-portal-prod
    ports:
      - "3000:3000"
    environment:
      - EDIT_PASSWORD=${EDIT_PASSWORD}
      - ADMIN_TZ=${ADMIN_TZ}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    volumes:
      - portal_data:/app/data
      - studies_data:/app/studies
    restart: unless-stopped

  caddy:
    image: caddy:latest
    container_name: caddy-proxy
    restart: unless-stopped
    ports:
      - "10.0.0.46:80:80"
      - "10.0.0.46:443:443"
    entrypoint: ["sh", "-c"]
    command:
      - |
        cat <<'EOF' > /tmp/Caddyfile
        razielzaarur.duckdns.org {
            reverse_proxy app:3000
        }
        http://:80 {
            @isPublicDomain header Host razielzaarur.duckdns.org
            redir @isPublicDomain https://{host}{uri} permanent
            reverse_proxy app:3000
        }
        EOF
        caddy run --config /tmp/Caddyfile
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

volumes:
  portal_data: {}
  caddy_data: {}
  caddy_config: {}
  studies_data:
    driver: local
    driver_opts:
      type: cifs
      o: "username=${CIFS_USER},password=${CIFS_PASS},vers=3.0,dir_mode=0777,file_mode=0777,nounix"
      device: "//100.88.173.17/RazielFolder/לימודים רזיאל"
