version: '3.8'

services:
  app:
    build: .
    container_name: study-portal-prod
    expose:
      - "3000"
    volumes:
      - portal_data:/app/data
      - studies_data:/app/studies
    restart: unless-stopped

  caddy:
    image: caddy:latest
    container_name: caddy-proxy
    restart: unless-stopped
    ports:
      - "10.0.0.46:80:80"
      - "10.0.0.46:443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

volumes:
  portal_data: {}
  caddy_data: {}
  caddy_config: {}
  studies_data:
    driver: local
    driver_opts:
      type: cifs
      o: "username=${CIFS_USER},password=${CIFS_PASS},vers=3.0,dir_mode=0777,file_mode=0777,nounix"
      device: "//100.88.173.17/RazielFolder/לימודים רזיאל"
