version: '3.8'

services:
  app:
    build: .
    container_name: study-portal
    ports:
      - "3000:3000"
    volumes:
      - portal_data:/app/data
      - studies_data:/app/studies
    restart: unless-stopped

volumes:
  portal_data: {}
  studies_data:
    driver: local
    driver_opts:
      type: cifs
      o: "username=Raziel,password=Raz123!@#,vers=3.0,dir_mode=0777,file_mode=0777,nounix"
      device: "//100.88.173.17/RazielFolder/לימודים רזיאל"
